# -*- coding: utf-8 -*-
"""Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUE0SRCEedPif3Oa-JAnJFE9y1fytcWi
"""

import streamlit as st
import pandas as pd
import joblib

# =====================
# SIDEBAR NAVIGATION
# =====================
st.set_page_config(page_title="Walmart Retail Dashboard", layout="wide")
st.sidebar.title("Walmart Retail Dashboard")
page = st.sidebar.radio(
    "Navigate",
    ["Home", "Classification", "Regression", "Time Series", "Association Rules"]
)

# =====================
# FUNCTIONS
# =====================

# -------- Classification --------
def load_class_data():
    return pd.read_csv('final_classification_predictions.csv')

def get_class_importance():
    df = pd.read_csv('final_classification_feature_importance.csv')
    return df.sort_values('importance', ascending=False).head(10)

# -------- Regression --------
def load_reg_data():
    return pd.read_csv('sample_predictions.csv')

def load_reg_model():
    return joblib.load('final_regression_pipeline.pkl')  # Load only

def get_reg_coefficients():
    model = load_reg_model()
    try:
        coef = model.named_steps['model'].coef_
        features = model.named_steps['preprocessor'].get_feature_names_out()
    except:
        coef = getattr(model, 'coef_', None)
        features = [f'Feature_{i}' for i in range(len(coef))]
    return pd.DataFrame({'feature': features, 'coefficient': coef})

def get_reg_importance():
    df = pd.read_csv('feature_importance.csv')
    return df.sort_values('importance', ascending=False).head(10)

# -------- Time Series --------
def load_ts_data():
    return pd.read_csv('final_time_series_forecast.csv')

def get_ts_importance():
    df = pd.read_csv('final_time_series_feature_importance.csv')
    return df.sort_values('importance', ascending=False).head(10)

# -------- Association Rules (placeholder) --------
def load_rules():
    return pd.read_csv('final_association_rules.csv')

def get_top_rules():
    df = load_rules()
    return df.sort_values(by=['lift', 'confidence'], ascending=False).head(10)

# =====================
# PAGE CONTENT
# =====================

if page == "Home":
    st.title("Smart AI Dashboard")
    st.markdown("""
    **Available Pipelines:**
    - Classification: prediction table + top 10 features
    - Regression: actual vs predicted + coefficients + top 10 features
    - Time Series: forecast + top 10 features
    - Association Rules: top 10 rules + lift vs confidence (placeholder)
    """)

elif page == "Classification":
    st.title("Classification Dashboard")

    st.subheader("Prediction Table")
    st.dataframe(load_class_data(), use_container_width=True)

    st.subheader("Top 10 Feature Importance")
    st.bar_chart(get_class_importance().set_index('feature'))

elif page == "Regression":
    st.title("Regression Dashboard")

    # Actual vs Predicted
    st.subheader("Actual vs Predicted")
    df = load_reg_data()
    st.line_chart(df.set_index(df.columns[0])[['Actual_Weekly_Sales', 'Predicted_Weekly_Sales']])

    # Model Coefficients
    st.subheader("Model Coefficients")
    st.dataframe(get_reg_coefficients(), use_container_width=True)

    # Top 10 Feature Importance
    st.subheader("Top 10 Feature Importance")
    st.bar_chart(get_reg_importance().set_index('feature'))

elif page == "Time Series":
    st.title("Time Series Dashboard")

    st.subheader("Actual vs Forecast")
    df_ts = load_ts_data()
    st.line_chart(df_ts.set_index('timestamp')[['actual', 'forecast']])

    st.subheader("Top 10 Feature Importance")
    st.bar_chart(get_ts_importance().set_index('feature'))

elif page == "Association Rules":
    st.title("Association Rules Dashboard")
    st.info("placeholder")
